### ISSUE TITLE
Windows lose focus when using mouse wheel as trigger

### ISSUE THREAD

**Issue by meelash** [nod5/TwoCamControl#4] opened 2018-08-16 06:38 UTC
I'm running into a problem specifically when using the mouse wheel as a trigger. At seemingly random intervals, the mouse wheel will rotate but either neither camera or one of the cameras will not fire. Alt-Tab into one of the command windows seems to release it from whatever stuck state it is in and it will then fire. Even triggering it multiple times will do nothing and then alt-tab to one of the windows will release it and it will trigger multiple times in rapid sequence.

I have experimented with positioning the mouse pointer on any of the three related windows, or off of them, somewhere else, but have not been able to notice any difference.

To reiterate, this happens at random intervals, like, after 30-40 pages. It doesn't appear to happen when using space bar as the trigger.

I'm not sure if this is related, but I've noticed sometimes the windows get "stuck" in focus and it is not possible to bring the other command window or the main window into focus by clicking on the window bar. By alt-tab, it will come into focus. Again, not sure if that is related.

Any of the following would be appreciated:

- confirmation that others have used it with the mouse wheel as a trigger for 1000+ pages and not run into this problem (meaning it is something specific to my setup)
- Any clues as to what could be the cause
- Any workaround

Now that I have a mouse wheel set up to trigger on my scanner, TwoCamControl is very close to being the peak efficiency scanning software for me. This is the last remaining issue!

**Comment by nod5** [comment] 2018-08-18 15:25
Thanks for reporting. I use a mouse wheel as trigger without running into that problem. 

> Alt-Tab into one of the command windows seems to release it from whatever stuck state it is in and it will then fire. 

Likely a timing issue in TwoCamControl's activation of the cmd windows. How quickly a window activates can vary with PC and system load which make issues with such commands tricky to test for/reproduce/troubleshoot.

I think the halt you describe is due to [`WinActivate`](
https://autohotkey.com/docs/commands/WinActivate.htm
)and [`WinWaitActive`](https://autohotkey.com/docs/commands/WinWaitActive.htm) on [lines 427-428](https://github.com/nod5/TwoCamControl/blob/master/TwoCamControl.ahk#L427)
TwoCamControl, unwisely, there waits _indefinitely_ for the cmd window to activate, so will get stuck if activation fails.

As a quick workaround try this [line 428](https://github.com/nod5/TwoCamControl/blob/master/TwoCamControl.ahk#L428) edit to add a 1 second timeout, which should prevent getting stuck.
`WinWaitActive, d=%y% ahk_exe cmd.exe ,, 1`

But as a side effect TwoCamControl may instead send strings meant for the unsuccessfully activated cmd window to whatever other window is still active. Might work out ok, might have unwanted effects.

A proper fix is to change the function `acti()` to check if activation worked and if so return true. And split all lines that call acti() so that later commands only fire if `acti()` returned true. I will add that proper fix, but don't have time right now.

> a problem specifically when using the mouse wheel as a trigger

Not sure why the issue would happen only with Mouse Wheel and not Space as both trigger the same commands. See line [736+](https://github.com/nod5/TwoCamControl/blob/master/TwoCamControl.ahk#L736). Is the mouse wheel perhaps turned in a way that generates many events in very quick sequence?

**Comment by nod5** [comment] 2018-08-30 15:47
Please check if release 2018-08-30 solves the issue

**Comment by nod5** [comment] 2018-10-04 19:02
Closing issue because release 2018-08-30 fix activation failure and freeze issue.  
Feedback welcome on if there is still a mouse wheel issue.

**Closed as completed** 2018-10-04 19:02 UTC
Labels: bug
